# syntax=docker/dockerfile:1
ARG BUILDER_IMAGE=maven:3.9.9-eclipse-temurin-17
ARG RUNNER_IMAGE=eclipse-temurin:17

FROM ${BUILDER_IMAGE} AS builder
RUN apt-get update && apt-get install -y unzip
COPY ./metaschema-cli/target/*metaschema-cli.zip /tmp/metaschema-cli.zip
WORKDIR /tmp
RUN unzip /tmp/metaschema-cli-*-metaschema-cli.zip -d /opt/metaschema-cli
RUN chmod +x /opt/metaschema-cli/bin/metaschema-cli

FROM ${RUNNER_IMAGE} AS runner
COPY --from=builder /opt/metaschema-cli /opt/metaschema-cli
RUN groupadd -r metaschema && \
    useradd -r -g metaschema -s /bin/false metaschema && \
    chown -R metaschema:metaschema /opt/metaschema-cli && \
    mkdir -p /app && \
    chown metaschema:metaschema /app
WORKDIR /app
USER metaschema
RUN /opt/metaschema-cli/bin/metaschema-cli --version
ENTRYPOINT [ "/opt/metaschema-cli/bin/metaschema-cli" ]
