name: Project Automation

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        with:
          project-url: https://github.com/orgs/metaschema-framework/projects/1
          github-token: ${{ secrets.ACCESS_TOKEN }}
